# NumPy

* Numerical Python
* http://www.numpy.org

* C언어로 구현된 파이썬 라이브러리(외부 라이브러리)
* 고성능 수치계산을 위해 만들어진 파이썬 패키지

**NumPy 모듈선언**

In [5]:
import numpy as np

In [7]:
np.__version__

'1.20.3'

**array**

In [9]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [10]:
data2 = [1, 2, 3.3, 5, 5]
data2

[1, 2, 3.3, 5, 5]

In [11]:
arr1 = np.array(data1)
arr1

array([1, 2, 3])

In [12]:
arr1.shape

(3,)

In [13]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [14]:
arr2.shape

(5,)

In [15]:
arr2.dtype

dtype('int32')

In [16]:
arr3 = np.array([1,2,3,3.5,4])
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [17]:
arr3.dtype

dtype('float64')

In [18]:
arr3.shape

(5,)

In [22]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr4.shape

(3, 3)

In [25]:
arr4.dtype

dtype('int32')

**arange 함수**

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,10,2)

: 

In [29]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
b1 = np.arange(12).reshape(3,4)
b1.shape

(3, 4)

In [31]:
b2 = np.arange(7).reshape(3,3)  # 크기가 맞지 않아서 오류발생

ValueError: cannot reshape array of size 7 into shape (3,3)

In [32]:
b3 = b1.reshape(4,3)
b3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**linspace()**

In [35]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [38]:
np.linspace(1,10).shape

(50,)

**특별한 형태의 배열**

In [42]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.zeros((3,5)).reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**대각요소(np.eye())**

In [46]:
# 3행 3열의 대각요소가 1인 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [48]:
np.eye(3,4, k=1, dtype=int) # 인덱스는 0부터 시작! k값에 따라 1열에 들어가있음

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [49]:
np.eye(3,4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [50]:
np.eye(3,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

**단위행렬 np.identity**

In [51]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

**초기화 되지 않은 배열 np.empty**

In [52]:
np.empty(4)

array([4.94065646e-324, 9.14950371e-304, 1.11555608e-118, 2.38369755e-311])

**astype()**

In [53]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [57]:
str_a1 = np.array(['1.5', '0.62', '2', '3.14', '3.141592'])
num_a1 = str_a1.astype('float32')
num_a1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592], dtype=float32)

In [55]:
str_a1.dtype

dtype('<U8')

In [58]:
num_a1.dtype

dtype('float32')

In [59]:
str_a2 = np.array(['1','2','3','4'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 2, 3, 4])

**실수형 배열을 정수형 배열로 반환**

In [60]:
num_f1 = np.array([10,20,0.549,4.75])
num_f1

array([10.   , 20.   ,  0.549,  4.75 ])

In [61]:
num_i1 = num_f1.astype(int)
num_i1

array([10, 20,  0,  4])

In [62]:
num_f1.dtype

dtype('float64')

**숫자형 배열을 문자열 배열로 변환**

In [63]:
num_f1.astype('U')

array(['10.0', '20.0', '0.549', '4.75'], dtype='<U32')

In [64]:
num_f1.astype('S')

array([b'10.0', b'20.0', b'0.549', b'4.75'], dtype='|S32')

**난수 배열 생성**

In [66]:
np.random.rand(10)
np.random.rand(2,5)

array([[0.88737863, 0.90075612, 0.36556823, 0.37058424, 0.0393426 ],
       [0.37457474, 0.57324982, 0.53007083, 0.29545533, 0.31460867]])

In [67]:
np.random.rand(2,3,4)

array([[[0.47380055, 0.44292222, 0.16152739, 0.15061502],
        [0.75854745, 0.51630903, 0.22267918, 0.93250208],
        [0.37935906, 0.57935348, 0.06123681, 0.24568419]],

       [[0.15948916, 0.11371943, 0.07340843, 0.80036712],
        [0.07660683, 0.23414141, 0.18146981, 0.00776774],
        [0.94187014, 0.51971722, 0.93855126, 0.26741612]]])

In [68]:
np.random.rand(2,4)

array([[0.02533094, 0.56635444, 0.77649921, 0.3470499 ],
       [0.19667023, 0.46402908, 0.15704285, 0.17525283]])

In [70]:
np.random.randint(10)

4

In [71]:
np.random.randint(10,20)

13

In [72]:
np.random.randint(10, 20, size=(3,5))

array([[12, 10, 14, 14, 12],
       [10, 10, 12, 13, 10],
       [17, 18, 17, 12, 12]])

**Array 연산**

In [74]:
arr1 = np.array([[1, 3, 4],[4, 3, 6]])
arr1

array([[1, 3, 4],
       [4, 3, 6]])

In [79]:
arr2 = np.arange(10,16).reshape(2,3)
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [80]:
print(arr1.shape, arr2.shape)

(2, 3) (2, 3)


In [81]:
arr1 + arr2

array([[11, 14, 16],
       [17, 17, 21]])

In [82]:
arr1 - arr2

array([[ -9,  -8,  -8],
       [ -9, -11,  -9]])

In [83]:
arr1 * arr2

array([[10, 33, 48],
       [52, 42, 90]])

In [84]:
arr1 / arr2

array([[0.1       , 0.27272727, 0.33333333],
       [0.30769231, 0.21428571, 0.4       ]])

In [85]:
arr2*2

array([[20, 22, 24],
       [26, 28, 30]])

In [86]:
arr2 >12

array([[False, False, False],
       [ True,  True,  True]])

**배열의 Broadcasting**

In [87]:
arr1

array([[1, 3, 4],
       [4, 3, 6]])

In [88]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [89]:
(arr1.shape, arr3.shape)

((2, 3), (3,))

In [90]:
arr1 + arr3

array([[11, 14, 16],
       [14, 14, 18]])

In [91]:
arr1**2

array([[ 1,  9, 16],
       [16,  9, 36]], dtype=int32)

day1 브로드캐스팅까지~!